trigger:
  - main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: "Build BSP"
  jobs:
    - job: android
      steps:
        - checkout: self
        - script: android\build.bat
          displayName: "Run Android build script (Windows)"

- stage: QA
  displayName: "Run QA Scripts"
  dependsOn: Build
  jobs:
    - job: qa
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: "3.x"
        - script: |
            cd qa-scripts
            python test_usb.py > ..\reports\usb_report.txt
            python test_internet.py > ..\reports\internet_report.txt
            python test_sdcard.py > ..\reports\sdcard_report.txt
          displayName: "Run Python QA Tests"
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: "reports"
            ArtifactName: "Reports"
            publishLocation: "Container"
