trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  ANDROID_DIR: 'Android'
  QA_SCRIPTS_DIR: 'QA_Scripts'

stages:
  - stage: Build
    displayName: 'Build Android BSP'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true

          - checkout: self

          - script: |
              echo "Starting Android BSP build..."
              ls $(ANDROID_DIR)
              # Add your Android build commands here, e.g., ./build.sh
            displayName: 'Build Android BSP'

  - stage: QA_Tests
    displayName: 'Run QA Scripts'
    dependsOn: Build
    jobs:
      - job: RunQATests
        displayName: 'QA Scripts Job'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true

          - checkout: self

          - script: |
              echo "Running QA Scripts..."
              python3 $(QA_SCRIPTS_DIR)/test_internet.py
              python3 $(QA_SCRIPTS_DIR)/test_usb.py
            displayName: 'Execute QA Scripts'

  - stage: Deploy
    displayName: 'Optional Deployment Stage'
    dependsOn: QA_Tests
    condition: succeeded()
    jobs:
      - job: DeployJob
        displayName: 'Deploy BSP / Artifacts'
        steps:
          - checkout: self
          - script: |
              echo "Deploying BSP artifacts..."
              # Add deployment steps here (e.g., upload to server, copy to storage)
            displayName: 'Deploy Artifacts'